<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Answers' => 'Ответы',
  'Multiple answers per user' => 'Множественный вариант ответа',
  'Please specify at least {min} answers!' => 'Пожалуйста, укажите как минимум {min} вариантов ответа',
  'Question' => 'Вопрос',
  'Name' => 'Имя',
  'Body' =>'Текст сообщения',
  'Select folder' => 'Выберите папку',
);
