<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Asked by me' => 'С моими ответами',
  'Creation time' => 'Дата добавления',
  'Display all' => 'Показать все',
  'Last update' => 'Последнее обновление',
  'No answered yet' => 'Еще не отвечены',
  'No poll found which matches your current filter(s)!' => 'Голосование по заданному фильтру не найдены',
  'Only private polls' => 'Закрытые голосования',
  'Only public polls' => 'Голосования для всех',
  'Filter' => 'Фильтр',
  'Sorting' => 'Сортировка',
  'View' => 'Вид',
  'List' => 'Список',
  'Table' => 'Таблица',
);
